### ISSUE TITLE
No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package

### ISSUE THREAD

**Issue by woodserino** [mattlyon93/face-comparison#2]
I'm getting the following error:

`ModuleNotFoundError: No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package`

when I try to run facecompare. So far I've tried changing keras and TF versions (as per https://stackoverflow.com/questions/58047454/how-to-fix-module-keras-backend-tensorflow-backend-has-no-attribute-is-tf) but I haven't found a solution that works yet.

Using tensorflow  2.3.0, keras 2.4.3 and python 3.8.5

**Comment by nikitosbobin** [comment]
I have the same problem. How to solve it?

**Comment by mattlyon93** [comment]
This error is caused due to the fact that TensorFlow/Keras have changed their APIs slightly since initially releasing this module.

I've removed/changed the offending lines of code, and fixed the specific versions of TensorFlow and Keras used, so this should now resolve the issue.

Please let me know if this has resolved the issue for you. To update to the latest release:
`pip install --upgrade face-compare`

**Comment by nikitosbobin** [comment]
Thanks for reactive solving problem. I'll try new version later today

**Comment by nikitosbobin** [comment]
This issue solved

**Comment by nikitosbobin** [comment]
This issue fixed
But I got new problem: _tensorflow.python.framework.errors_impl.InvalidArgumentError:  Default MaxPoolingOp only supports NHWC on device type CPU_

I have installed **intel-tensorflow**, but it have no any effect

My configuration:
Windows 10
Intel Core i5-6500
Nvidia GTX 1060 6GB (without installed CUDA)

**Comment by mattlyon93** [comment]
> This issue fixed
> But I got new problem: _tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU_

Yes, I encountered this problem too. `NHWC` refers to the order in which the data is stored so Number x Height x Width x Channels. As it turns out this model is trained on data that is in `NCHW` format or Number x Channels x Height x Width.

This problem is fixed by installing the Intel optimization TensorFlow via
`pip install intel-tensorflow`

More information for which can be found [here](https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html). I've also added this as a known issue to the `README.md` page.

Hope this helps.

**Comment by nikitosbobin** [comment]
Yes, I have installed intel-tensorflow, but error remained

**Comment by mattlyon93** [comment]
Hmm, my only suggestion would be to see if any of the other installation options on [the intel optimization for tensorflow page](https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html) work.

Using the `intel-tensorflow` in Windows 10 Ubuntu Subshell worked for me.

Since you have an NVIDIA graphics card, is installing CUDA an option for you?

**Comment by Sailkiki** [comment]
I can help you, the TF2 has already delete the module of set_session, i give your a example

this is wrong
`from keras import backend as K
tf_session = tf.compat.v1.Session(graph=tf.compat.v1.get_default_graph(),config=config)
K.set_session(tf_session)
`

and the complie shew that 
AttributeError: module 'keras.backend' has no attribute 'set_session'

you can fix it by follows
`tf_session = tf.compat.v1.Session(graph=tf.compat.v1.get_default_graph(),config=config)
tf.compat.v1.keras.backend.set_session(tf_session)
`

**Comment by ramesh-mahesh** [comment]
Hello Team,

Please help me in resolving the issue.

Python:  3.10.6
Pip:  22.0.2 
Tensorflow: 2.11.0
Keras:  2.11.0


Error:
Traceback (most recent call last):
  File "/usr/local/bin/compare_faces.py", line 8, in <module>
    from face_compare.model import facenet_model, img_to_encoding
  File "/usr/local/lib/python3.10/dist-packages/face_compare/model.py", line 6, in <module>
    import keras.backend.tensorflow_backend as tfback
ModuleNotFoundError: No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package

**Comment by FurkanGozukara** [comment]
> tf_session

where is this file we need to check? i have this problem

https://github.com/m-lyon/face-comparison/issues/5#issuecomment-1526143778

**Comment by FurkanGozukara** [comment]
> Hmm, my only suggestion would be to see if any of the other installation options on [the intel optimization for tensorflow page](https://software.intel.com/content/www/us/en/develop/articles/intel-optimization-for-tensorflow-installation-guide.html) work.
> 
> Using the `intel-tensorflow` in Windows 10 Ubuntu Subshell worked for me.
> 
> Since you have an NVIDIA graphics card, is installing CUDA an option for you?

i have nvidia and CUDA installed
still not working

**Comment by m-lyon** [comment]
Are you sure CUDA is enabled and visible to tensorflow? you can check via `tf.config.list_physical_devices('GPU')`
