### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by eveen91** [mattlyon93/face-comparison#22]
during installation i I encountered a problem:
 Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Running from numpy source directory.
      <string>:425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Traceback (most recent call last):
        File "C:\Users\Evan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Evan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Evan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\Evan\AppData\Local\Temp\pip-build-env-ogn9wlzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 376, in prepare_metadata_for_build_wheel
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\Evan\AppData\Local\Temp\pip-build-env-ogn9wlzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Evan\AppData\Local\Temp\pip-build-env-ogn9wlzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 450, in <module>
        File "<string>", line 429, in setup_package
        File "C:\Users\Evan\AppData\Local\Temp\pip-install-_rgyglze\numpy_c12c8e1dd3784fb09c5f856e1faa6823\numpy\distutils\core.py", line 26, in <module>
          from numpy.distutils.command import config, config_compiler, \
          ...<2 lines>...
               install_clib
        File "C:\Users\Evan\AppData\Local\Temp\pip-install-_rgyglze\numpy_c12c8e1dd3784fb09c5f856e1faa6823\numpy\distutils\command\config.py", line 20, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "C:\Users\Evan\AppData\Local\Temp\pip-install-_rgyglze\numpy_c12c8e1dd3784fb09c5f856e1faa6823\numpy\distutils\mingw32ccompiler.py", line 34, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

any ideas how to fix it?

Python 3.13.0

**Comment by pavkum7** [comment]
Getting the same error both in windows and mac. Can some one please assist

**Comment by Qambar-Abbas** [comment]
> during installation i I encountered a problem: Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [31 lines of output] Running from numpy source directory. :425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates Traceback (most recent call last): File "C:\Users\Evan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() ~~~~^^ File "C:\Users\Evan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ~~~~^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Evan\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 149, in prepare_metadata_for_build_wheel return hook(metadata_directory, config_settings) File "C:\Users\Evan\AppData\Local\Temp\pip-build-env-ogn9wlzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 376, in prepare_metadata_for_build_wheel self.run_setup() ~~~~~~~~~~~~~~^^ File "C:\Users\Evan\AppData\Local\Temp\pip-build-env-ogn9wlzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup super().run_setup(setup_script=setup_script) ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Evan\AppData\Local\Temp\pip-build-env-ogn9wlzo\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup exec(code, locals()) ~~~~^^^^^^^^^^^^^^^^ File "", line 450, in File "", line 429, in setup_package File "C:\Users\Evan\AppData\Local\Temp\pip-install-_rgyglze\numpy_c12c8e1dd3784fb09c5f856e1faa6823\numpy\distutils\core.py", line 26, in from numpy.distutils.command import config, config_compiler, ...<2 lines>... install_clib File "C:\Users\Evan\AppData\Local\Temp\pip-install-_rgyglze\numpy_c12c8e1dd3784fb09c5f856e1faa6823\numpy\distutils\command\config.py", line 20, in from numpy.distutils.mingw32ccompiler import generate_manifest File "C:\Users\Evan\AppData\Local\Temp\pip-install-_rgyglze\numpy_c12c8e1dd3784fb09c5f856e1faa6823\numpy\distutils\mingw32ccompiler.py", line 34, in from distutils.msvccompiler import get_build_version as get_build_msvc_version ModuleNotFoundError: No module named 'distutils.msvccompiler' [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> any ideas how to fix it?
> 
> Python 3.13.0



The installation issue might be due to incompatibility between Python 3.13 and the numpy build process, specifically the absence of the distutils module, which has been removed from the standard library starting Python 3.12.

You should create a new python or conda env and use Python 3.9–3.11 for best compatibility — 
the latest stable version that supports distutils and is compatible with most packages like numpy, tensorflow, and older FaceNet-based codebases is Python 3.11.
