### ISSUE TITLE
IndexError: tuple index out of range? 

### ISSUE THREAD

**Issue by amuuth** [mattlyon93/face-comparison#4]
I have a fresh install of face-compare with Keras 2.4.2 and tensorflow 2.3.0. 

When I pass two images to compare_faces.py, I get this output - 
`line 9, in get_face
    x, y, w, h = tuple(map(tuple, face_box))[0]
IndexError: tuple index out of range
`

I am guessing the issue is with keras image_data_format, but face-compare isn't working for me on the default, or when I try changing it to channels_first or channels_last. 

Any advice?

**Comment by mattlyon93** [comment]
This code actually pertains to `cv2`, which in this instance is used to identify the part of the image which is a face. 
The line below unpacks the co-ordinates of the bounding box for the identified face.
```python
x, y, w, h = tuple(map(tuple, face_box))[0]
```

I suspect that is the face detection function producing something unexpected. Potentially not detecting a face at all.

What version of `cv2` are you running?

Also, if you run the code below (filling in `YOUR_IMG` with the two images used that presented this error), what is the output?
```python
import cv2

YOUR_IMG = 'path/to/img'

img = cv2.imread(YOUR_IMG , 1)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
face_boxes = face_cascade.detectMultiScale(img)
print(face_boxes.shape)
```

**Comment by amuuth** [comment]
Thanks Matt - yep, the issue is that the images I need to compare aren't of a high enough resolution to detect faces. Other packages I've tried have a similar issue though, all opencv based. The only facial detection package I've found which can detect faces in the images I need to compare is AWS Rekognition, but I can't find much information on what computer vision library they are using. 

Here's an example image I need to compare - do you think you could see if you have any luck with detecting a face in it? 

![index](https://user-images.githubusercontent.com/54684365/94585412-fae54980-024d-11eb-903f-32d85ffef49a.jpeg)

![pers1-2](https://user-images.githubusercontent.com/54684365/94585330-df7a3e80-024d-11eb-88cb-d75434c30eb3.jpeg)

**Comment by amuuth** [comment]
Oops, I didn't answer your questions. 

`print(cv2.__version__)` outputs 4.4.0.

Using an image of Obama - 
![obama](https://user-images.githubusercontent.com/54684365/94721416-d78cce00-0323-11eb-8551-c3b89cfe07b6.jpg)

I get the following output from this code: 

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print(face_boxes.shape)
AttributeError: 'tuple' object has no attribute 'shape'

```

**Comment by mattlyon93** [comment]
> gives me this output:
> ```Traceback (most recent call last):
 > File "test.py", line 9, in <module>
  >  print(face_boxes.shape)
> AttributeError: 'tuple' object has no attribute 'shape'`
>```

Yes, so as there is no face detected, the return from the `face_cascade.detectMultiScale` method is an empty tuple.

I believe that the reason it can't detect a face is more likely due to the mask the person is wearing, rather than the resolution of the image. To do AI face detection with people wearing masks you would need a model that was trained on pictures of faces with masks on, and FaceNet (which is used in the recognition part of this module) is definitely not.
